include:
  project: gardenlinux/gardenlinux-package-build
  file: pipeline/pipeline.yml

variables:
  SOURCE_NAME: cyrus-sasl2
  # We can't cross-build right now, disable arm64 because of that
  BUILD_ARCH_ARM64: ''
